In [1]:
import numpy as np

In [2]:
l=['prat',1,2,3,4]

In [3]:
type(l)

list

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
np.array([3,4,5,6,7,3.0])

array([3., 4., 5., 6., 7., 3.])

In [9]:
a=np.array([[1,2],[3,4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [12]:
# Extracting 4
a[1,1]

4

In [15]:
#Extracting 4
a1=np.array([3,4,5,6,7,3.0])

In [16]:
a1

array([3., 4., 5., 6., 7., 3.])

In [17]:
a1[1]

4.0

In [25]:
# Changing the dimension
a3=np.array([1,2,3,4],ndmin=3)

In [26]:
a3

array([[[1, 2, 3, 4]]])

In [30]:
#Extracting 1
a3[0][0][0]

1

In [31]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [32]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [33]:
# Matrices
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [34]:
type(np.mat([1,2,3,4,5]))

numpy.matrix

In [35]:
# Returns array
a=[1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [37]:
# Returns array
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
# Returns matrix
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [42]:
# Returns matrix - asanyarray checks whether something is availble in anyform of array or not
np.asanyarray(np.mat([1,2,3,4,5]))


matrix([[1, 2, 3, 4, 5]])

In [43]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
np.fromfunction(lambda i,j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [46]:
np.fromfunction(lambda i,j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [47]:
# Convering the above into matrix
np.mat(np.fromfunction(lambda i,j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [52]:
# Creating 3d array
np.fromfunction(lambda i,j,z : i*j*z, (4,4,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2],
        [0, 3]],

       [[0, 0],
        [0, 2],
        [0, 4],
        [0, 6]],

       [[0, 0],
        [0, 3],
        [0, 6],
        [0, 9]]])

In [54]:
# Creating 3d array
# How to read this array(This the combination of 3 matrices with the dimension (3,2))
np.fromfunction(lambda i,j,z : i*j*z, (3,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [57]:
# 4d array
# How to read(([2*2 dimension - 3 array]- 4 combination))
np.fromfunction(lambda i,j,z,p : i*j*z*p, (4,3,2,2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [60]:
# Find dimension of array
a=np.fromfunction(lambda i,j,z : i*j*z, (4,3,2), dtype=int)

In [62]:
a.ndim

3

In [64]:
# Size represents total number of elemts in the array
a.size

24

In [65]:
a.shape

(4, 3, 2)

In [66]:
a.dtype

dtype('int32')

In [70]:
# Convering array into dataframe
import pandas as pd
a=np.fromfunction(lambda i,j : i*j, (4,3), dtype=int)

In [71]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [77]:
#Creating 400 rows and 100 colun dataframe
a=np.fromfunction(lambda i,j : i*j, (400,100), dtype=int)

In [78]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [79]:
# Random function
np.random.rand(100,4)

array([[0.29424682, 0.08592718, 0.73686423, 0.12621529],
       [0.709027  , 0.60761343, 0.48164775, 0.46561903],
       [0.15205614, 0.46683772, 0.00259985, 0.7277944 ],
       [0.4040876 , 0.7384905 , 0.44548893, 0.27950998],
       [0.96571599, 0.25899513, 0.90461521, 0.3588646 ],
       [0.06137534, 0.31462986, 0.05495215, 0.58654028],
       [0.28046482, 0.48301239, 0.62204894, 0.16074604],
       [0.49907929, 0.45116603, 0.33980915, 0.71135384],
       [0.11462253, 0.8033807 , 0.49721893, 0.40928368],
       [0.23001992, 0.51957993, 0.99681143, 0.34488703],
       [0.1051361 , 0.1794559 , 0.20279412, 0.69545197],
       [0.7712696 , 0.41138136, 0.4233785 , 0.12695181],
       [0.63693673, 0.21657531, 0.56565897, 0.75375893],
       [0.62816991, 0.52393262, 0.13118184, 0.419752  ],
       [0.61559859, 0.58300045, 0.37646298, 0.22970996],
       [0.50038081, 0.70412594, 0.1257701 , 0.73069463],
       [0.88838579, 0.42818156, 0.36846323, 0.91282964],
       [0.97713016, 0.9420159 ,

In [81]:
# Random integer between numbers
np.random.randint(4,50)

7

In [85]:
# Gives average of the numbers will be zero and SD of the number will be 1
np.random.randn(4,5)

array([[ 0.20691802, -0.6625165 , -1.54688643, -0.23253242,  0.41855238],
       [ 1.33288606,  1.09493586,  1.4660673 ,  0.426358  , -0.50319119],
       [ 0.2729965 ,  0.06748045,  0.48249925,  0.16147169,  0.0574077 ],
       [ 1.12655888,  1.29199279, -0.01404276,  0.95213162,  2.1778754 ]])

In [86]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.719142  1.715304  1.046223 -0.882836  0.781010
1  0.916650 -1.818405 -0.293775  1.972284  1.633483
2 -0.088276  0.580403  0.223584  1.870464 -0.405265
3  1.604115 -0.811422  1.386576  2.121516 -1.004748

In [92]:
# Reshape the data
a=np.fromfunction(lambda i,j,z : i*j*z, (4,3,2), dtype=int)
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [93]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [94]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [95]:
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [98]:
# -1 gives rest of the dimentions apart from 4 so its basically 6(any negative number)
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [99]:
# arange 
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [100]:
a1=np.arange(4,10,.2)

In [105]:
#Slicing operation
a1[1:4]

array([4.2, 4.4, 4.6])

In [106]:
arr= np.random.randn(4,5)

In [107]:
arr

array([[-0.6141531 , -0.19022398, -1.19020104, -0.86454375,  1.29018909],
       [-0.77860596, -1.50003513,  2.13691027,  1.41836968, -0.13670239],
       [ 0.95332778, -0.9065598 ,  1.51944155, -2.60798397, -1.75047043],
       [ 1.07149758,  0.3595892 , -1.52821721, -0.57752595, -1.27326567]])

In [110]:
# Data > 0.5
arr[arr >0.5]

array([1.29018909, 2.13691027, 1.41836968, 0.95332778, 1.51944155,
       1.07149758])

In [111]:
arr

array([[-0.6141531 , -0.19022398, -1.19020104, -0.86454375,  1.29018909],
       [-0.77860596, -1.50003513,  2.13691027,  1.41836968, -0.13670239],
       [ 0.95332778, -0.9065598 ,  1.51944155, -2.60798397, -1.75047043],
       [ 1.07149758,  0.3595892 , -1.52821721, -0.57752595, -1.27326567]])

In [112]:
arr[[1,2],[2]]

array([2.13691027, 1.51944155])

In [115]:
arr= np.random.randn(8,5)

In [120]:
arr

array([[-0.67722967, -0.02220479,  0.27733422,  1.61005527, -0.0498978 ],
       [ 0.91413469, -0.4520936 , -1.19505732, -0.1497844 , -0.50915288],
       [-0.13488984, -0.78506302, -1.87622758,  0.67517308,  0.53765604],
       [-0.60258609,  1.32568033, -1.45958311,  1.21519572,  0.46809771],
       [-1.22699994,  1.11099133,  0.55388763,  0.38388932, -0.28498361],
       [-1.09831825, -0.22343897,  1.00162166, -0.92092935,  0.90088846],
       [-0.38374606, -1.4081715 , -0.67580168,  0.73752347, -0.9572422 ],
       [ 0.9144075 , -0.61101939, -1.61333932,  1.0638983 , -0.86403993]])

In [127]:
arr[1:8,0:3]

array([[ 0.91413469, -0.4520936 , -1.19505732],
       [-0.13488984, -0.78506302, -1.87622758],
       [-0.60258609,  1.32568033, -1.45958311],
       [-1.22699994,  1.11099133,  0.55388763],
       [-1.09831825, -0.22343897,  1.00162166],
       [-0.38374606, -1.4081715 , -0.67580168],
       [ 0.9144075 , -0.61101939, -1.61333932]])

In [128]:
arr[1:8,[0,1,2]]

array([[ 0.91413469, -0.4520936 , -1.19505732],
       [-0.13488984, -0.78506302, -1.87622758],
       [-0.60258609,  1.32568033, -1.45958311],
       [-1.22699994,  1.11099133,  0.55388763],
       [-1.09831825, -0.22343897,  1.00162166],
       [-0.38374606, -1.4081715 , -0.67580168],
       [ 0.9144075 , -0.61101939, -1.61333932]])

In [129]:
# Replace 0.91413469 with something else
a2=arr[1:8,[0,1,2]]

In [131]:
a2[0][0]=345

In [132]:
a2

array([[ 3.45000000e+02, -4.52093603e-01, -1.19505732e+00],
       [-1.34889844e-01, -7.85063019e-01, -1.87622758e+00],
       [-6.02586089e-01,  1.32568033e+00, -1.45958311e+00],
       [-1.22699994e+00,  1.11099133e+00,  5.53887631e-01],
       [-1.09831825e+00, -2.23438971e-01,  1.00162166e+00],
       [-3.83746056e-01, -1.40817150e+00, -6.75801681e-01],
       [ 9.14407502e-01, -6.11019395e-01, -1.61333932e+00]])

In [133]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [134]:
a

array([[1, 2],
       [3, 4]])

In [135]:
b

array([[2, 3],
       [4, 5]])

In [137]:
# element wise/index multiplication
a*b

array([[ 2,  6],
       [12, 20]])

In [139]:
# Matrix Multiplication(column of 1st and row of 2nd have to be same size)
a@b

array([[10, 13],
       [22, 29]])

In [140]:
m=a@b

In [141]:
m/0

<ipython-input-141-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [142]:
# Zeros function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [144]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [145]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [147]:
# Adding scaler with Vector(Broadcasting)
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [151]:
# Random dataset with very less Magnitude
np.empty((4,5))

array([[0.81753766, 1.03330205, 1.35573963, 1.73112852, 0.29162559],
       [0.81232444, 0.55544635, 0.15917194, 0.288191  , 2.54835575],
       [1.48127309, 0.57580768, 0.14333767, 0.21388242, 0.96841346],
       [0.47749831, 1.45869216, 0.93147617, 0.36108643, 0.15222282]])

In [152]:
np.empty((4,5,2))

array([[[0.67722967, 0.02220479],
        [0.27733422, 1.61005527],
        [0.0498978 , 0.91413469],
        [0.4520936 , 1.19505732],
        [0.1497844 , 0.50915288]],

       [[0.13488984, 0.78506302],
        [1.87622758, 0.67517308],
        [0.53765604, 0.60258609],
        [1.32568033, 1.45958311],
        [1.21519572, 0.46809771]],

       [[1.22699994, 1.11099133],
        [0.55388763, 0.38388932],
        [0.28498361, 1.09831825],
        [0.22343897, 1.00162166],
        [0.92092935, 0.90088846]],

       [[0.38374606, 1.4081715 ],
        [0.67580168, 0.73752347],
        [0.9572422 , 0.9144075 ],
        [0.61101939, 1.61333932],
        [1.0638983 , 0.86403993]]])

In [158]:
# Generate the numbers between the given numbers with that many numbers given
# Numbers are equaly divided between (2,6)
np.linspace(2,6,40)

array([2.        , 2.1025641 , 2.20512821, 2.30769231, 2.41025641,
       2.51282051, 2.61538462, 2.71794872, 2.82051282, 2.92307692,
       3.02564103, 3.12820513, 3.23076923, 3.33333333, 3.43589744,
       3.53846154, 3.64102564, 3.74358974, 3.84615385, 3.94871795,
       4.05128205, 4.15384615, 4.25641026, 4.35897436, 4.46153846,
       4.56410256, 4.66666667, 4.76923077, 4.87179487, 4.97435897,
       5.07692308, 5.17948718, 5.28205128, 5.38461538, 5.48717949,
       5.58974359, 5.69230769, 5.79487179, 5.8974359 , 6.        ])

In [162]:
#Convert it to multidimension
r=np.linspace(2,6,40)

In [163]:
r.reshape(10,4)

array([[2.        , 2.1025641 , 2.20512821, 2.30769231],
       [2.41025641, 2.51282051, 2.61538462, 2.71794872],
       [2.82051282, 2.92307692, 3.02564103, 3.12820513],
       [3.23076923, 3.33333333, 3.43589744, 3.53846154],
       [3.64102564, 3.74358974, 3.84615385, 3.94871795],
       [4.05128205, 4.15384615, 4.25641026, 4.35897436],
       [4.46153846, 4.56410256, 4.66666667, 4.76923077],
       [4.87179487, 4.97435897, 5.07692308, 5.17948718],
       [5.28205128, 5.38461538, 5.48717949, 5.58974359],
       [5.69230769, 5.79487179, 5.8974359 , 6.        ]])

In [165]:
# upper bound excluded
np.linspace(2,6,10, endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [167]:
# stepsize =0.4
np.linspace(2,6,10, endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [171]:
# log of number
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [172]:
# log of number
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [173]:
a=np.arange(16).reshape(4,4)

In [174]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [175]:
# Maximum number
a.max()

15

In [177]:
a=np.arange(4,40).reshape(3,6,2)

In [178]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [179]:
a.max()

39

In [182]:
# Column wise it gives maximum value(multiple numbers got)
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [212]:
a=np.arange(4,40).reshape(6,6)

In [213]:
a


array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [214]:
# Row wise gives maximum value
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [215]:
# Column wise gives maximum value
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [216]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [217]:
# Power function
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [218]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [219]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [220]:
b=np.array([2,3,1,2,3,2])

In [221]:
# row wise Broadcasting
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [227]:
# column wise Broadcasting
b1=np.array([2,3,1,2,3,2])

In [228]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [229]:
b1.T

array([2, 3, 1, 2, 3, 2])

In [230]:
a+b1

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [231]:
# Its giving same result 

In [232]:
# we have to make 2D array
b1=np.array([2,3,1,2,3,2])

In [233]:
b1=b1.reshape(1,-1)

In [234]:
b1

array([[2, 3, 1, 2, 3, 2]])

In [235]:
# Now we can transpose
b1.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [237]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [240]:
# Now we get the column wise addition value
a+b1.T

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [241]:
# Square function
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [242]:
#Exponent function
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [244]:
#Log function
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [253]:
# Deep copy and Shallow copy
x=np.array([1,2,3])

In [254]:
# Shallow copy
y=x

In [255]:
y

array([1, 2, 3])

In [256]:
# Deep copy
z=np.copy(x) # Here it is copying to the new location

In [257]:
z

array([1, 2, 3])

In [258]:
x[0]=100

In [259]:
y

array([100,   2,   3])

In [260]:
z # As here it pointing to the different location hence evef if after we assign x[0]=100, it is not going to change 

array([1, 2, 3])

In [261]:
x

array([100,   2,   3])

In [262]:
# x,y point to the same address so value has changed for both


In [263]:
# So we can confirm by checking by identity of object
id(z)

2241289636240

In [264]:
id(x)

2241307665776

In [265]:
id(y)

2241307665776

In [266]:

id(x[0])

2241295031824

In [267]:
id(y[0])

2241295031600

In [268]:
# If we check index/element wise both identities are different

In [270]:
# Analysis
id(x[0])==id(y[0])

True

In [272]:
#Also
id(x[0])==id(y[1])

True